baseURL = 'https://jwei3156.github.io/'
locale = 'zh-cn'
title = 'Jw Blog'
theme = "PaperMod"

[params]
    DisableSpecial1stPost = true
    ShowReadingTime = false
    ShowShareButtons = false
    ShowCodeCopyButtons = true
    mainSections = ["computerbasics", "ctfbasic", "security"]

# ==========================================
# Main navigation
# ==========================================

[[menu.main]]
    name = "归档"
    url = "/archives/"
    weight = 10
